/**
 * The Node env shim — the D1 HTTP API, R2 SigV4 and the Map-backed KV that let
 * the ingest run from GitHub Actions (plan 33 wave 2b).
 *
 *     node workers/orbit-ingest/test/env-node.test.mjs
 *
 * Two things here are worth more than the rest.
 *
 * **The SigV4 vectors come from botocore, not from this signer.** A hand-rolled
 * signer checked only against itself proves nothing; these expectations were
 * generated by `botocore.auth.SigV4Auth` for the same request and pasted in, so
 * the test fails if the two implementations ever disagree.
 *
 * **D1 is exercised against a real SQLite.** The fake fetch hands the SQL this
 * shim generates to `node:sqlite` — the same trick as test/sqlite.test.mjs —
 * which is what proves the thing the shim could most plausibly get wrong:
 * numbers surviving as numbers. The REST API types its `params` array as
 * *strings*, so the shim inlines literals instead, and this is where that
 * decision is checked rather than assumed.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

import {
  sqlLiteral, inlineParams, signV4, D1Http, R2S3, memoryKV, createEnv,
} from '../scripts/env-node.mjs';
import { CITATION, OBJECT_UPSERT_SQL, deriveObjectRow, buildGroupArtifacts, GROUPS, upsertObjects } from '../src/derive.js';
import { runGP } from '../src/index.js';
import { ingestSatcat } from '../src/ingest-satcat.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../../..');
const SCHEMA = fs.readFileSync(path.join(ROOT, 'd1/orbit.sql'), 'utf8');
const raw = (n) => fs.readFileSync(path.join(HERE, '../fixtures', n), 'utf8');

const results = [];
async function test(name, fn) {
  try { await fn(); results.push(true); console.log('  PASS  ' + name); }
  catch (e) { results.push(false); console.log('  FAIL  ' + name + '\n        ' + (e && e.message)); }
}

const NOW = '2026-07-27T10:00:00.000Z';
const nosleep = async () => {};

/* ── A D1 that is actually SQLite ───────────────────────────────────────────
 *
 * Splitting on `;` has to respect string literals, exactly as SQLite's own
 * parser does — an OBJECT_NAME containing a semicolon would otherwise cut a
 * statement in half, and it would do so only for that one row.
 */
function splitStatements(sql) {
  const out = [];
  let cur = '';
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (inString) {
      cur += c;
      if (c === "'") { if (sql[i + 1] === "'") cur += sql[++i]; else inString = false; }
      continue;
    }
    if (c === "'") { inString = true; cur += c; continue; }
    if (c === ';') { if (cur.trim()) out.push(cur.trim()); cur = ''; continue; }
    cur += c;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

const READS = /^\s*(SELECT|PRAGMA|WITH|EXPLAIN)/i;

function sqliteD1(db, { log = [] } = {}) {
  return async (_url, init) => {
    const { sql } = JSON.parse(init.body);
    const statements = splitStatements(sql);
    log.push(statements);
    const result = [];
    for (const s of statements) {
      const stmt = db.prepare(s);
      if (READS.test(s)) {
        result.push({ success: true, results: stmt.all(), meta: {} });
      } else {
        const info = stmt.run();
        result.push({
          success: true,
          results: [],
          meta: { last_row_id: Number(info.lastInsertRowid), changes: Number(info.changes) },
        });
      }
    }
    return new Response(JSON.stringify({ success: true, errors: [], messages: [], result }), {
      headers: { 'Content-Type': 'application/json' },
    });
  };
}

function freshDb() {
  const db = new DatabaseSync(':memory:');
  db.exec(SCHEMA);
  return db;
}

function httpDb(db, extra = {}) {
  return new D1Http({
    accountId: 'acct', databaseId: 'dbid', apiToken: 'tok',
    fetch: sqliteD1(db, extra), sleep: nosleep, ...extra.opts,
  });
}

/* ── SQL literals ───────────────────────────────────────────────────────── */

console.log('\n-- parameters become SQL literals, not REST strings --');

await test('scalars render to the right literal forms', () => {
  assert.equal(sqlLiteral(null), 'NULL');
  assert.equal(sqlLiteral(undefined), 'NULL');
  assert.equal(sqlLiteral(132.594), '132.594');
  assert.equal(sqlLiteral(0), '0');
  assert.equal(sqlLiteral(NaN), 'NULL');        // never the string "NaN"
  assert.equal(sqlLiteral(Infinity), 'NULL');
  assert.equal(sqlLiteral(true), '1');
  assert.equal(sqlLiteral("ISS (ZARYA)"), "'ISS (ZARYA)'");
});

await test("an apostrophe in a name is doubled, not escaped with a backslash", () => {
  // SQLite has no backslash escape; a C-style escape would end the literal
  // early and turn the rest of the row into syntax.
  assert.equal(sqlLiteral("O'BRIEN SAT"), "'O''BRIEN SAT'");
});

await test('objects are refused rather than stringified to [object Object]', () => {
  assert.throws(() => sqlLiteral({ a: 1 }), /stringify it first/);
});

await test('a ? inside a string literal is not a placeholder', () => {
  assert.equal(
    inlineParams("UPDATE t SET name = 'what?' WHERE id = ?", [7]),
    "UPDATE t SET name = 'what?' WHERE id = 7");
});

await test('arity mismatches throw instead of producing valid-looking SQL', () => {
  assert.throws(() => inlineParams('SELECT ? , ?', [1]), /more \? than params/);
  assert.throws(() => inlineParams('SELECT ?', [1, 2]), /2 params for 1 placeholders/);
  assert.throws(() => inlineParams('SELECT ?', []), /unbound \?/);
});

/* ── D1 over HTTP, against SQLite ───────────────────────────────────────── */

console.log('\n-- D1Http drives a real SQLite through the HTTP shape --');

await test('prepare/bind/run/all/first behave like the binding', async () => {
  const db = freshDb();
  const d1 = httpDb(db);

  const res = await d1.prepare('INSERT INTO api_calls (ts, class, url) VALUES (?, ?, ?)')
    .bind(1753610000000, 'gp', 'https://example.test/q').run();
  assert.equal(res.meta.last_row_id, 1, 'last_row_id is what spacetrack.js logs against');

  const all = await d1.prepare('SELECT * FROM api_calls').all();
  assert.equal(all.results.length, 1);
  assert.equal(all.results[0].class, 'gp');

  const first = await d1.prepare('SELECT class FROM api_calls WHERE ts = ?')
    .bind(1753610000000).first();
  assert.equal(first.class, 'gp');

  assert.equal(await d1.prepare('SELECT * FROM api_calls WHERE ts = ?').bind(0).first(), null);
});

await test('numbers survive the round trip as numbers — the REST params trap', async () => {
  const db = freshDb();
  const d1 = httpDb(db);
  const gp = JSON.parse(raw('sample_gp.json'));

  await d1.batch(gp.map((r) => d1.prepare(OBJECT_UPSERT_SQL).bind(...deriveObjectRow(r, NOW))));

  // Space-Track sends "PERIOD": "132.594" as a string. If the shim shipped that
  // through the REST API's string-typed params array, this would be 'text' and
  // every numeric group predicate would silently return nothing.
  const t = db.prepare(
    "SELECT typeof(PERIOD) p, typeof(NORAD_CAT_ID) n, typeof(OBJECT_NAME) o FROM objects LIMIT 1").get();
  assert.equal(t.p, 'real');
  assert.equal(t.n, 'integer');
  assert.equal(t.o, 'text');

  // and the consequence that actually matters
  const geo = db.prepare('SELECT COUNT(*) c FROM objects WHERE PERIOD BETWEEN 1430 AND 1450').get();
  assert.ok(geo.c >= 0);
  const leo = db.prepare('SELECT COUNT(*) c FROM objects WHERE PERIOD < 128').get();
  assert.ok(leo.c > 0, 'LEO objects must be findable by a numeric comparison');
});

await test('batch() is ONE request carrying every statement', async () => {
  const db = freshDb();
  const log = [];
  const d1 = new D1Http({
    accountId: 'a', databaseId: 'b', apiToken: 'c', fetch: sqliteD1(db, { log }), sleep: nosleep,
  });
  const gp = JSON.parse(raw('sample_gp.json'));
  await d1.batch(gp.map((r) => d1.prepare(OBJECT_UPSERT_SQL).bind(...deriveObjectRow(r, NOW))));

  assert.equal(log.length, 1, 'a batch must not become one request per row');
  assert.equal(log[0].length, gp.length);
  assert.equal(d1.requests, 1);
});

await test('a semicolon inside a name does not split the statement', async () => {
  const db = freshDb();
  const d1 = httpDb(db);
  const gp = JSON.parse(raw('sample_gp.json'));
  const row = { ...gp[0], OBJECT_NAME: 'WEIRD; NAME (TEST)', NORAD_CAT_ID: '99991' };
  await d1.batch([d1.prepare(OBJECT_UPSERT_SQL).bind(...deriveObjectRow(row, NOW))]);
  const got = db.prepare('SELECT OBJECT_NAME FROM objects WHERE NORAD_CAT_ID = 99991').get();
  assert.equal(got.OBJECT_NAME, 'WEIRD; NAME (TEST)');
});

await test('re-running an ingest upserts rather than duplicating', async () => {
  const db = freshDb();
  const d1 = httpDb(db);
  const gp = JSON.parse(raw('sample_gp.json'));
  const send = (when) =>
    d1.batch(gp.map((r) => d1.prepare(OBJECT_UPSERT_SQL).bind(...deriveObjectRow(r, when))));

  await send(NOW);
  const n1 = db.prepare('SELECT COUNT(*) c FROM objects').get().c;
  await send('2026-07-27T16:00:00.000Z');
  const n2 = db.prepare('SELECT COUNT(*) c FROM objects').get().c;
  assert.equal(n1, n2);
  assert.equal(db.prepare('SELECT first_seen FROM objects LIMIT 1').get().first_seen, NOW,
    'first_seen must survive the second write');
});

await test('upsertObjects skips rows whose GP_ID has not changed', async () => {
  // The delta window overlaps by design, so most rows in a 6-hourly run are
  // elsets 18 SPCS has not actually regenerated since last time — re-writing
  // those was the single largest driver of D1 write-row usage (see CLAUDE.md).
  const db = freshDb();
  const d1 = httpDb(db);
  const gp = JSON.parse(raw('sample_gp.json'));

  const batch1 = gp.map((r) => deriveObjectRow(r, NOW));
  const written1 = await upsertObjects(d1, batch1);
  assert.equal(written1, gp.length, 'first run: every row is new, all written');

  // Re-send the identical rows (same GP_ID) — nothing changed upstream.
  const batch2 = gp.map((r) => deriveObjectRow(r, '2026-07-27T16:00:00.000Z'));
  const written2 = await upsertObjects(d1, batch2);
  assert.equal(written2, 0, 'second run: identical GP_ID, nothing should be written');
  assert.equal(
    db.prepare('SELECT updated_at FROM objects LIMIT 1').get().updated_at, NOW,
    'a skipped row must not have updated_at bumped',
  );

  // Bump GP_ID on one row, as a real re-generated elset would carry — that one
  // row, and only that one, should be written this run.
  const changed = { ...gp[0], GP_ID: Number(gp[0].GP_ID || 0) + 1 };
  const batch3 = [deriveObjectRow(changed, '2026-07-27T18:00:00.000Z'), ...gp.slice(1).map((r) => deriveObjectRow(r, '2026-07-27T18:00:00.000Z'))];
  const written3 = await upsertObjects(d1, batch3);
  assert.equal(written3, 1, 'only the row with a changed GP_ID should be written');
});

await test('a 500 is retried; a 400 is not', async () => {
  let calls = 0;
  const flaky = new D1Http({
    accountId: 'a', databaseId: 'b', apiToken: 'c', sleep: nosleep,
    fetch: async () => {
      calls++;
      if (calls < 3) return new Response('upstream hiccup', { status: 503 });
      return new Response(JSON.stringify({ success: true, result: [{ results: [], meta: {} }] }));
    },
  });
  await flaky.prepare('SELECT 1').all();
  assert.equal(calls, 3);

  let hard = 0;
  const bad = new D1Http({
    accountId: 'a', databaseId: 'b', apiToken: 'c', sleep: nosleep,
    fetch: async () => { hard++; return new Response('bad sql', { status: 400 }); },
  });
  await assert.rejects(() => bad.prepare('SELECT 1').all(), /D1 HTTP 400/);
  assert.equal(hard, 1, 'a broken statement retried is three chances to half-apply');
});

await test('an API-level error surfaces instead of looking like an empty result', async () => {
  const d1 = new D1Http({
    accountId: 'a', databaseId: 'b', apiToken: 'c', sleep: nosleep,
    fetch: async () => new Response(JSON.stringify({
      success: false, errors: [{ code: 7500, message: 'no such table: objects' }], result: [],
    })),
  });
  await assert.rejects(() => d1.prepare('SELECT 1').all(), /no such table/);
});

/* ── R2 / SigV4 ─────────────────────────────────────────────────────────── */

console.log('\n-- SigV4 matches botocore, byte for byte --');

const VECTOR = {
  accessKeyId: 'AKIDEXAMPLE1234567890',
  secretAccessKey: 'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY',
  url: 'https://abc123.r2.cloudflarestorage.com/orbit-data/tle/spacetrack/stations.txt',
  body: 'ISS (ZARYA)\n1 25544U\n2 25544U\n',
  now: new Date('2026-07-27T10:11:12.000Z'),
  headers: {
    'content-length': '30',
    'content-type': 'text/plain; charset=utf-8',
    'x-amz-meta-citation': 'Data source: Space-Track.org (USSPACECOM).',
  },
  // Generated by botocore 1.42.64:
  //   SigV4Auth(Credentials(ak, sk), 's3', 'auto').signature(string_to_sign, req)
  signature: '8013a38f1be1acf92b07a5546c19c83786d8b03b78b6c1f67c4ab38f44e988b2',
  signedHeaders: 'content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-citation',
};

await test('the Authorization header equals botocore\'s for the same request', () => {
  const signed = signV4({
    method: 'PUT', url: VECTOR.url, headers: VECTOR.headers, payload: Buffer.from(VECTOR.body),
    accessKeyId: VECTOR.accessKeyId, secretAccessKey: VECTOR.secretAccessKey, now: VECTOR.now,
  });
  assert.equal(
    signed.Authorization,
    `AWS4-HMAC-SHA256 Credential=${VECTOR.accessKeyId}/20260727/auto/s3/aws4_request, ` +
    `SignedHeaders=${VECTOR.signedHeaders}, Signature=${VECTOR.signature}`);
  assert.equal(signed['x-amz-date'], '20260727T101112Z');
  assert.equal(signed['x-amz-content-sha256'],
    '367c393e2081077f0c6927cc34ae21df29a02b474a324c23abd3d7e1098c8286');
});

await test('changing one byte of the payload changes the signature', () => {
  const sign = (payload) => signV4({
    method: 'PUT', url: VECTOR.url, headers: VECTOR.headers, payload,
    accessKeyId: VECTOR.accessKeyId, secretAccessKey: VECTOR.secretAccessKey, now: VECTOR.now,
  }).Authorization;
  assert.notEqual(sign(Buffer.from(VECTOR.body)), sign(Buffer.from(VECTOR.body + ' ')));
});

console.log('\n-- R2S3 puts the artifacts the globe reads --');

function captureR2() {
  const sent = [];
  const r2 = new R2S3({
    accountId: 'abc123', bucket: 'orbit-data',
    accessKeyId: 'ak', secretAccessKey: 'sk', sleep: nosleep,
    fetch: async (url, init) => { sent.push({ url, init }); return new Response('', { status: 200 }); },
  });
  r2.sent = sent;
  return r2;
}

await test('put() targets bucket/key and carries content type + metadata', async () => {
  const r2 = captureR2();
  await r2.put('tle/spacetrack/stations.txt', 'ISS (ZARYA)\n', {
    httpMetadata: { contentType: 'text/plain; charset=utf-8' },
    customMetadata: { citation: CITATION, generated: NOW },
  });
  const [{ url, init }] = r2.sent;
  assert.equal(url, 'https://abc123.r2.cloudflarestorage.com/orbit-data/tle/spacetrack/stations.txt');
  assert.equal(init.method, 'PUT');
  assert.equal(init.headers['content-type'], 'text/plain; charset=utf-8');
  assert.equal(init.headers['x-amz-meta-citation'], CITATION);
  assert.match(init.headers.Authorization, /^AWS4-HMAC-SHA256 Credential=ak\//);
  assert.equal(r2.puts, 1);
});

await test('the citation is ASCII, so it can be an S3 metadata header at all', () => {
  // A curly quote or an em dash here would throw inside fetch() at 17:20 UTC
  // and take the whole artifact rebuild with it. The citation is a condition of
  // the redistribution approval, so it is not droppable — it has to stay plain.
  // eslint-disable-next-line no-control-regex
  assert.doesNotMatch(CITATION, /[^\x20-\x7e]/);
});

await test('non-ASCII metadata is rejected where the key is still nameable', async () => {
  const r2 = captureR2();
  await assert.rejects(
    () => r2.put('k.txt', 'x', { customMetadata: { note: 'em—dash' } }),
    /non-ASCII/);
});

await test('get() returns null on 404 rather than throwing', async () => {
  const r2 = new R2S3({
    accountId: 'a', bucket: 'b', accessKeyId: 'ak', secretAccessKey: 'sk', sleep: nosleep,
    fetch: async () => new Response('', { status: 404 }),
  });
  assert.equal(await r2.get('missing.json'), null);
});

await test('list() parses ListObjectsV2 XML into the Workers binding shape', async () => {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
  <IsTruncated>true</IsTruncated>
  <Contents><Key>brief/2026-08-01.json</Key></Contents>
  <Contents><Key>brief/2026-08-02.json</Key></Contents>
  <NextContinuationToken>tok-1</NextContinuationToken>
</ListBucketResult>`;
  const sent = [];
  const r2 = new R2S3({
    accountId: 'a', bucket: 'orbit-data', accessKeyId: 'ak', secretAccessKey: 'sk', sleep: nosleep,
    fetch: async (url, init) => { sent.push({ url, init }); return new Response(xml, { status: 200 }); },
  });

  const page = await r2.list({ prefix: 'brief/' });
  assert.deepEqual(page.objects, [{ key: 'brief/2026-08-01.json' }, { key: 'brief/2026-08-02.json' }]);
  assert.equal(page.truncated, true);
  assert.equal(page.cursor, 'tok-1');
  assert.equal(sent[0].url, 'https://a.r2.cloudflarestorage.com/orbit-data/?list-type=2&prefix=brief%2F');
});

await test('list() omits cursor on the final page so rebuildIndex stops looping', async () => {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
  <IsTruncated>false</IsTruncated>
  <Contents><Key>brief/2026-08-03.json</Key></Contents>
</ListBucketResult>`;
  const r2 = new R2S3({
    accountId: 'a', bucket: 'orbit-data', accessKeyId: 'ak', secretAccessKey: 'sk', sleep: nosleep,
    fetch: async () => new Response(xml, { status: 200 }),
  });
  const page = await r2.list({ prefix: 'brief/' });
  assert.equal(page.truncated, false);
  assert.equal(page.cursor, undefined);
});

await test('list() sends the continuation-token cursor on the next request', async () => {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult><IsTruncated>false</IsTruncated></ListBucketResult>`;
  const sent = [];
  const r2 = new R2S3({
    accountId: 'a', bucket: 'orbit-data', accessKeyId: 'ak', secretAccessKey: 'sk', sleep: nosleep,
    fetch: async (url) => { sent.push(url); return new Response(xml, { status: 200 }); },
  });
  await r2.list({ prefix: 'brief/', cursor: 'tok-1' });
  assert.match(sent[0], /continuation-token=tok-1/);
});

/* ── KV ─────────────────────────────────────────────────────────────────── */

console.log('\n-- KV is a Map, and that is enough --');

await test('get/put round trip, and expirationTtl is accepted and ignored', async () => {
  const kv = memoryKV();
  assert.equal(await kv.get('spacetrack:cookie'), null);
  await kv.put('spacetrack:cookie', 'chocolatechip=abc', { expirationTtl: 5400 });
  assert.equal(await kv.get('spacetrack:cookie'), 'chocolatechip=abc');
});

/* ── createEnv ──────────────────────────────────────────────────────────── */

console.log('\n-- createEnv fails loudly on a missing secret --');

await test('a missing secret names itself', () => {
  assert.throws(() => createEnv({ CLOUDFLARE_ACCOUNT_ID: 'a' }), /ORBIT_D1_DATABASE_ID is not set/);
  assert.throws(() => createEnv({}), /CLOUDFLARE_ACCOUNT_ID is not set/);
});

await test('a full environment builds all three bindings', () => {
  const env = createEnv({
    CLOUDFLARE_ACCOUNT_ID: 'acct', CLOUDFLARE_API_TOKEN: 'tok',
    ORBIT_D1_DATABASE_ID: 'dbid', R2_ACCESS_KEY_ID: 'ak', R2_SECRET_ACCESS_KEY: 'sk',
    SPACETRACK_IDENTITY: 'a@b.c', SPACETRACK_PASSWORD: 'p',
  });
  assert.equal(typeof env.ORBIT_DB.prepare, 'function');
  assert.equal(typeof env.ORBIT_R2.put, 'function');
  assert.equal(typeof env.ORBIT_KV.get, 'function');
  assert.equal(env.SPACETRACK_BASE, 'https://www.space-track.org');
});

/* ── The whole job, through the shim ────────────────────────────────────── */

console.log('\n-- runGP end to end: fixture upstream, SQLite D1, captured R2 --');

await test('a GP run lands rows, writes bundles and logs the call', async () => {
  const db = freshDb();
  const gpBody = raw('sample_gp.json');

  const env = {
    ORBIT_DB: httpDb(db),
    ORBIT_R2: captureR2(),
    ORBIT_KV: memoryKV({ 'spacetrack:cookie': 'chocolatechip=test' }),
    SPACETRACK_IDENTITY: 'a@b.c',
    SPACETRACK_PASSWORD: 'p',
    SPACETRACK_BASE: 'https://spacetrack.test',
  };

  const realFetch = globalThis.fetch;
  globalThis.fetch = async (url) => {
    assert.match(String(url), /spacetrack\.test/, 'the ingest must not reach the real API');
    return new Response(gpBody, { headers: { 'Content-Type': 'application/json' } });
  };
  let report;
  try { report = await runGP(env); } finally { globalThis.fetch = realFetch; }

  assert.ok(report.ok, JSON.stringify(report.steps));
  const ingest = report.steps.find((s) => s.name === 'ingest-gp');
  assert.equal(ingest.rows, JSON.parse(gpBody).length);
  assert.equal(db.prepare('SELECT COUNT(*) c FROM objects').get().c, ingest.rows);

  // The api_calls row is what the budget guard reads on the next run.
  const call = db.prepare("SELECT * FROM api_calls WHERE class = 'gp'").get();
  assert.equal(call.status, 200);
  assert.equal(call.rows, ingest.rows);

  // All group predicates ran against the shim without erroring. The fixture
  // is the twenty oldest catalog objects — Vanguards and Echo debris — so every
  // count is legitimately zero, and buildGroupArtifacts deliberately writes no
  // bundle for an empty group rather than blanking a good one. The bundle write
  // itself is covered below, where a matching row exists.
  const artifacts = report.steps.find((s) => s.name === 'artifacts');
  assert.equal(Object.keys(artifacts.groups).length, Object.keys(GROUPS).length);

  const keys = env.ORBIT_R2.sent.map((s) => s.url);
  assert.ok(keys.some((k) => k.includes('/feed/latest.json')), 'the feed must be written');
});

console.log('\n-- ingestSatcat: skips rows that have not actually changed --');

function mockSatcatFetch(body) {
  return async (url) => {
    assert.match(String(url), /spacetrack\.test/, 'the ingest must not reach the real API');
    return new Response(body, { headers: { 'Content-Type': 'application/json' } });
  };
}

await test('a re-sent SATCAT delta with no real changes writes nothing', async () => {
  const db = freshDb();
  const satcatBody = raw('sample_satcat.json');
  const rows = JSON.parse(satcatBody);

  const env = {
    ORBIT_DB: httpDb(db),
    ORBIT_KV: memoryKV({ 'spacetrack:cookie': 'chocolatechip=test' }),
    SPACETRACK_BASE: 'https://spacetrack.test',
  };

  const realFetch = globalThis.fetch;
  globalThis.fetch = mockSatcatFetch(satcatBody);
  let first;
  try { first = await ingestSatcat(env); } finally { globalThis.fetch = realFetch; }
  assert.equal(first.written, rows.length, 'first run: every row is new, all written');

  // Re-send the identical rows under a new FILE cursor position — as a normal
  // delta re-send would, since Space-Track's window overlaps by design.
  globalThis.fetch = mockSatcatFetch(satcatBody);
  let second;
  try { second = await ingestSatcat(env); } finally { globalThis.fetch = realFetch; }
  assert.equal(second.written, 0, 'second run: nothing actually changed, nothing written');
  assert.equal(second.changes, 0, 'no satcat_change events for an unchanged re-send');
});

await test('a genuinely changed SATCAT row is written; the rest are skipped', async () => {
  const db = freshDb();
  const rows = JSON.parse(raw('sample_satcat.json'));

  const env = {
    ORBIT_DB: httpDb(db),
    ORBIT_KV: memoryKV({ 'spacetrack:cookie': 'chocolatechip=test' }),
    SPACETRACK_BASE: 'https://spacetrack.test',
  };

  const realFetch = globalThis.fetch;
  globalThis.fetch = mockSatcatFetch(JSON.stringify(rows));
  try { await ingestSatcat(env); } finally { globalThis.fetch = realFetch; }

  const bumped = rows.map((r, i) => (i === 0 ? { ...r, OBJECT_NAME: 'RENAMED OBJECT' } : r));
  globalThis.fetch = mockSatcatFetch(JSON.stringify(bumped));
  let out;
  try { out = await ingestSatcat(env); } finally { globalThis.fetch = realFetch; }
  assert.equal(out.written, 1, 'only the row whose fields actually changed should be written');
  assert.equal(
    db.prepare('SELECT OBJECT_NAME FROM satcat WHERE NORAD_CAT_ID = ?').get(Number(rows[0].NORAD_CAT_ID)).OBJECT_NAME,
    'RENAMED OBJECT',
  );
});

await test('a group with members becomes a 3LE bundle carrying the citation', async () => {
  const db = freshDb();
  const env = { ORBIT_DB: httpDb(db), ORBIT_R2: captureR2() };

  // The ISS, by NORAD 25544 — the object the stations group exists for.
  db.prepare(`INSERT INTO objects (NORAD_CAT_ID, OBJECT_NAME, OBJECT_TYPE, TLE_LINE1, TLE_LINE2)
              VALUES (25544, 'ISS (ZARYA)', 'PAYLOAD', '1 25544U 98067A', '2 25544  51.6')`).run();

  const counts = await buildGroupArtifacts(env, { slugs: ['stations'] });
  assert.equal(counts.stations, 1);

  const [{ url, init }] = env.ORBIT_R2.sent;
  assert.ok(url.endsWith('/tle/spacetrack/stations.txt'), url);
  assert.equal(init.headers['x-amz-meta-citation'], CITATION);
  // Bare name line, not TLE_LINE0 — the '0 ' 3LE prefix would label the object
  // "0 ISS (ZARYA)" on the globe.
  assert.equal(init.body.toString('utf8'), 'ISS (ZARYA)\n1 25544U 98067A\n2 25544  51.6\n');
});

/* ── Report ─────────────────────────────────────────────────────────────── */

const failed = results.filter((r) => !r).length;
console.log(`\n${results.length - failed}/${results.length} passed`);
process.exit(failed ? 1 : 0);
